### ISSUE TITLE
No strings attached?

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf5-json#2]
What about compound field names and enumeration keys?

ascii_string        ::=  **TBD**
char_string         ::=  **TBD**   <-- Do we need this?
utf8_string         ::=  **TBD**
hdf5_path_name      ::=  **TBD**
hdf5_path_name_list ::=  **TBD**
url                 ::=  **TBD**
url_fragment        ::=  **TBD**
url_path            ::=  **TBD**

**Comment by jreadey** [comment]
Gerd, is this still an open issue?

**Comment by gheber** [comment]
I don't know. Have to go back and refresh my memory.

**Comment by ajelenak** [comment]
Problem no more. Closing.
