### ISSUE TITLE
UTF8 Strings not being converted correctly

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf5-json#25]
UTF8 strings get converted to ASCII.

**Comment by gheber** [comment]
What do you mean? ASCII is a subset of UTF-8. Do you mean non-ASCII characters are not rendered correctly?

**Comment by jreadey** [comment]
I mean that UTF-8 strings are getting corrupted when saved to hdf5.

**Comment by jreadey** [comment]
Fixed with commit: 50a39da26423f6f463db5bf44afafb899c8b25fb.
See test case hdf5dbTest.testWriteUnicodeAttribute
