### ISSUE TITLE
link_name and unicode

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/hdf5-json#33]
The grammar has this for link_name:   

```
  ascii_string_wo_slash | unicode_string_wo_slash 
```

What is the intended distinction here?  The JSON RFC says that all strings should be in unicode using utf-8.

**Comment by jreadey** [comment]
This question also applies to creationProperties for attributes (this came up in issue #37).
As with link names, I wouldn't think the encoding attribute adds any value.

**Comment by ajelenak** [comment]
Character encoding information of link or attribute names in HDF5/JSON is important in cases where JSON strings may contain Unicode code points that cannot be encoded in the specified encoding.

Closing this issue since link and attribute name encoding info is supported.
