### ISSUE TITLE
testing h5 file equivalence...

### ISSUE THREAD

**Issue by manor** [HDFGroup/hdf5-json#36]
To verify my installation of hdf5-json I ran:

```
python h5tojson.py ../data/hdf5/tall.h5 > tall.json
python jsontoh5.py tall.json tall.h5
```

But then to check that they were correct I ran:

```
diff tall.h5 ../data/hdf5/tall.h5
```

and I got:

```
Binary files tall.h5 and ../data/hdf5/tall.h5 differ
```
I am assuming the contents are effectively equivalent modulo some irrelevant timestamp or something... What is the correct way to check that the process succeeded?

**Comment by jreadey** [comment]
Two HDF5 files even if created via the same sequence of commands, won't be identical.

To verify the files are equivalent, you can compare the h5dump output of the two files.
