### ISSUE TITLE
Report fill value only if deliberately set

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hdf5-json#38]
`jsontoh5` currently reports fill value every time regardless if it is set or default. I suggest utilizing [`h5py.h5p.PropDCID.fill_value_defined()`](http://api.h5py.org/h5p.html#h5py.h5p.PropDCID.fill_value_defined) and only reporting fill value in output JSON if the method reports the value `h5d.FILL_VALUE_USER_DEFINED`.

**Comment by jreadey** [comment]
This got fixed in this commit: https://github.com/HDFGroup/hdf5-json/commit/b4e0dea4f88c6535bbe50e0b3a6ed3b9ea6526bf.
