### ISSUE TITLE
h5tojson fails to convert file that has loop among groups.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5-json#40]
Test file: https://s3.amazonaws.com/hdfgroup/data/hdf5test/countries.h5

**Comment by jreadey** [comment]
The problem was actually a failed conversion of numpy boolean types.  This is fixed in https://github.com/HDFGroup/hdf5-json/commit/6a13b2aca0730e56f47df54e9a247f47f717e433 and now countries.h5 converts to json successfully.
