### ISSUE TITLE
Source for h5json-1.1.0 is unavailable

### ISSUE THREAD

**Issue by Xarthisius** [HDFGroup/hdf5-json#57]
Right now there's only a binary wheel at https://pypi.python.org/pypi/h5json
Could you also please tag commits that were released?

**Comment by jreadey** [comment]
Sure - I've just uploaded to pypi: https://pypi.python.org/pypi?:action=pkg_edit&name=h5json.  I've also create tags for 1.1.0 and 1.1.1.

Let me know if you have any problems.

**Comment by jreadey** [comment]
Closing this issue.
