### ISSUE TITLE
Installation problem with h5serv

### ISSUE THREAD

**Issue by mohammadsamani** [HDFGroup/hdf5-json#67]
I am trying to follow these instruction to install the h5serv: https://h5serv.readthedocs.io/en/latest/Installation/ServerSetup.html
I use the git command to download the source codes. I think there's a problem on this line, when it says: From here cd to “server” (or “h5serv-master/server” if you extracted from ZIP file).
Instead of "server", the subfolder inside h5serv is also called h5serv, and that is where app.py is.
When I run app.py from there, I get the following message:

$ python app.py
Traceback (most recent call last):
  File "app.py", line 40, in <module>
    import h5serv.config as config
ImportError: No module named h5serv.config

Now I can go to the source code and remove every instance of "h5serv." from all the python files, and finally app.py runs successfully, but I never saw the message "Starting event loop on port: 5000"
What am I doing wrong?

**Comment by jreadey** [comment]
I think the Windows instructions got updated at some point, but not the Linux/OSX ones.  I've updated the server setup.rst file: https://github.com/HDFGroup/h5serv/blob/develop/docs/Installation/ServerSetup.rst - basically you just run "python h5serv" now.

Let me know if this works for you.

**Comment by mohammadsamani** [comment]
Yes. That worked. Thank you!
