### ISSUE TITLE
h5tojson_test raises "no attribute 'get_create_plist'" exception while converting several test files

### ISSUE THREAD

**Issue by cmholm-lbto** [HDFGroup/hdf5-json#69]
After cloning and "sudo python setup.py install", ran "python testall.py".
h5tojson_test failed while converting the following files with the error _AttributeError: 'h5py.h5t.TypeCompoundID' object has no attribute 'get_create_plist'_

- committed_type.h5 
- compound_committed.h5
- namedtype.h5
- sample.h5

> Traceback (most recent call last):
>   File "../../h5json/h5tojson/h5tojson.py", line 248, in <module>
>     main()
>   File "../../h5json/h5tojson/h5tojson.py", line 244, in main
>     dumper.dumpFile()
>   File "../../h5json/h5tojson/h5tojson.py", line 202, in dumpFile
>     self.dumpDatatypes()
>   File "../../h5json/h5tojson/h5tojson.py", line 184, in dumpDatatypes
>     item = self.dumpDatatype(uuid)
>   File "../../h5json/h5tojson/h5tojson.py", line 173, in dumpDatatype
>     attributes = self.dumpAttributes('datatypes', uuid)
>   File "../../h5json/h5tojson/h5tojson.py", line 55, in dumpAttributes
>     attr_list = self.db.getAttributeItems(col_name, uuid)
>   File "/usr/lib/python2.7/site-packages/h5json-1.1.3-py2.7.egg/h5json/hdf5db.py", line 1219, in getAttributeItems
>     for name in obj.attrs:
>   File "/usr/lib/python2.7/site-packages/h5py-2.9.0-py2.7-linux-x86_64.egg/h5py/_hl/attrs.py", line 257, in __iter__
>     cpl = self._id.get_create_plist()
> AttributeError: 'h5py.h5t.TypeCompoundID' object has no attribute 'get_create_plist'

Environment:
Fedora release 30
h5py    2.9.0
HDF5    1.10.4
Python  2.7.16 (default, Apr 30 2019, 15:54:43) 
[GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.16.3

**Comment by ajelenak** [comment]
This does not happen with current [master branch](https://github.com/HDFGroup/hdf5-json/tree/c9494a26ada12037b79e1d3aa06db2cdf9913fcf) code. Closing this issue.
