### ISSUE TITLE
Provide examples of variable-length of object reference attribute and compound type attribute with object reference and 32-bit integer.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hdf5-json#9]
This example will be helpful for dimension scale APIs.

**Comment by gheber** [comment]
I've created an example and sent it onto Joe.

**Comment by jreadey** [comment]
Can you the example to the docs?

**Comment by gheber** [comment]
Sure, once it's been vetted...

**Comment by hyoklee** [comment]
I have a question. Does x1 (size 2) and x2 (size 2) together make the 3rd dimension of size 4 in your example? Anyway, I think this kind of dim scale cannot be supported by netCDF. Can you create another example that has only x1 (size 4)?

**Comment by jreadey** [comment]
There's an extraneous comma at the end of line 250 in dim_scale.json.

**Comment by gheber** [comment]
Joe, no x1 and x2 are two alternative scales for the third dimension of data (4x3x2). y1 (3) and z1 (4) are the other dimensions. Just deleting x2 should do the trick.

**Comment by hyoklee** [comment]
Thanks @gheber for clarification. That makes perfect sense.

**Comment by gheber** [comment]
That still leaves the question, "What does netCDF support?"

**Comment by hyoklee** [comment]
netCDF supports netCDF-4-Python-created files  and augeos5-tool-augmented HDF-EOS5 files but not yours [1]. Here are possibilities of read failure by netCDF-Java tools:

1) Your example does not have actual data.
2) Two dim scales are attached.

Since your JSON example looks good enough for my purpose, I will not investigate further why netCDF fails to read your example data. 

[1] https://confluence.hdfgroup.uiuc.edu/display/~hyoklee/2015/03/10/Dimension+Scale
